version: '3'

services:
    main:
        build:
            context: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./app:/app
        ports:
            - 8088:8000
        env_file:
            - ./env/django.env
