version: '3'

services:
    main:
        build:
            context: .
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./app:/app
        ports:
            - 8088:8000
        env_file:
            - ./env/django.env
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=12345678
        depends_on:
          - db

    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345678